/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI704643086 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI956301393 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI956301399 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217741.base = NTI33555184;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555184;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555184;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555184;
var NNI956301399 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI956301393, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI956301399.node = NNI956301399;
var NNI704643086 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI704643086.node = NNI704643086;

function mnewString(len_33557025) {
        return new Array(len_33557025);
  

  
}

function toJSStr(s_33556923) {
  var result_33556924 = null;

    var res_33556965 = newSeq_33556941((s_33556923).length);
    var i_33556966 = 0;
    var j_33556967 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556966 < (s_33556923).length)) break Label2;
          var c_33556968 = s_33556923[i_33556966];
          if ((c_33556968 < 128)) {
          res_33556965[j_33556967] = String.fromCharCode(c_33556968);
          i_33556966 += 1;
          }
          else {
            var helper_33556981 = newSeq_33556941(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556982 = c_33556968.toString(16);
                  if ((((code_33556982) == null ? 0 : (code_33556982).length) == 1)) {
                  helper_33556981.push("%0");;
                  }
                  else {
                  helper_33556981.push("%");;
                  }
                  
                  helper_33556981.push(code_33556982);;
                  i_33556966 += 1;
                  if ((((s_33556923).length <= i_33556966) || (s_33556923[i_33556966] < 128))) {
                  break Label3;
                  }
                  
                  c_33556968 = s_33556923[i_33556966];
                }
            };
++excHandler;
            try {
            res_33556965[j_33556967] = decodeURIComponent(helper_33556981.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556965[j_33556967] = helper_33556981.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556967 += 1;
        }
    };
    if (res_33556965.length < j_33556967) { for (var i = res_33556965.length ; i < j_33556967 ; ++i) res_33556965.push(null); }
               else { res_33556965.length = j_33556967; };
    result_33556924 = res_33556965.join("");

  return result_33556924;

}

function raiseException(e_33556675, ename_33556676) {
    e_33556675.name = ename_33556676;
    if ((excHandler == 0)) {
    unhandledException(e_33556675);
    }
    
    throw e_33556675;

  
}

function addInt(a_33557072, b_33557073) {
        var result = a_33557072 + b_33557073;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557346, a_33557347, b_33557348) {
  var result_33557349 = 0;

  BeforeRet: {
    if (((a_33557347 <= i_33557346) && (i_33557346 <= b_33557348))) {
    result_33557349 = i_33557346;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557349;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557290, src_33557291, ti_33557292) {
  var result_33557301 = null;

    switch (ti_33557292.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557281(ti_33557292))) {
      result_33557301 = src_33557291;
      }
      else {
        result_33557301 = [src_33557291[0], src_33557291[1]];
      }
      
      break;
    case 19:
            if (dest_33557290 === null || dest_33557290 === undefined) {
        dest_33557290 = {};
      }
      else {
        for (var key in dest_33557290) { delete dest_33557290[key]; }
      }
      for (var key in src_33557291) { dest_33557290[key] = src_33557291[key]; }
      result_33557301 = dest_33557290;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557292.base == null))) {
      result_33557301 = nimCopy(dest_33557290, src_33557291, ti_33557292.base);
      }
      else {
      if ((ti_33557292.kind == 17)) {
      result_33557301 = (dest_33557290 === null || dest_33557290 === undefined) ? {m_type: ti_33557292} : dest_33557290;
      }
      else {
        result_33557301 = (dest_33557290 === null || dest_33557290 === undefined) ? {} : dest_33557290;
      }
      }
      nimCopyAux(result_33557301, src_33557291, ti_33557292.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557291)) { 
        if(dest_33557290 === null || dest_33557290 === undefined || dest_33557290.length != src_33557291.length) {
          dest_33557290 = new src_33557291.constructor(src_33557291);
        } else {
          dest_33557290.set(src_33557291, 0);
        }
        result_33557301 = dest_33557290;
      } else {
        if (src_33557291 === null) {
          result_33557301 = null;
        }
        else {
          if (dest_33557290 === null || dest_33557290 === undefined || dest_33557290.length != src_33557291.length) {
            dest_33557290 = new Array(src_33557291.length);
          }
          result_33557301 = dest_33557290;
          for (var i = 0; i < src_33557291.length; ++i) {
            result_33557301[i] = nimCopy(result_33557301[i], src_33557291[i], ti_33557292.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557291 === null) {
        result_33557301 = null;
      }
      else {
        if (dest_33557290 === null || dest_33557290 === undefined || dest_33557290.length != src_33557291.length) {
          dest_33557290 = new Array(src_33557291.length);
        }
        result_33557301 = dest_33557290;
        for (var i = 0; i < src_33557291.length; ++i) {
          result_33557301[i] = nimCopy(result_33557301[i], src_33557291[i], ti_33557292.base);
        }
      }
    
      break;
    case 28:
            if (src_33557291 !== null) {
        result_33557301 = src_33557291.slice(0);
      }
    
      break;
    default: 
      result_33557301 = src_33557291;
      break;
    }

  return result_33557301;

}

function chckIndx(i_33557341, a_33557342, b_33557343) {
  var result_33557344 = 0;

  BeforeRet: {
    if (((a_33557342 <= i_33557341) && (i_33557341 <= b_33557343))) {
    result_33557344 = i_33557341;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557341, a_33557342, b_33557343);
    }
    
  };

  return result_33557344;

}

function makeNimstrLit(c_33556917) {
      var result = [];
  for (var i = 0; i < c_33556917.length; ++i) {
    result[i] = c_33556917.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33557076, b_33557077) {
        var result = a_33557076 - b_33557077;
    checkOverflowInt(result);
    return result;
  

  
}

function cstrToNimstr(c_33556920) {
      var ln = c_33556920.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556920.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556920.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33557080, b_33557081) {
        var result = a_33557080 * b_33557081;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_33557130, b_33557131) {
    var Temporary1;

  var result_33557132 = 0;

  BeforeRet: {
    if ((b_33557131 <= a_33557130)) {
    Temporary1 = a_33557130;
    }
    else {
    Temporary1 = b_33557131;
    }
    
    result_33557132 = Temporary1;
    break BeforeRet;
  };

  return result_33557132;

}

function nimMin(a_33557126, b_33557127) {
    var Temporary1;

  var result_33557128 = 0;

  BeforeRet: {
    if ((a_33557126 <= b_33557127)) {
    Temporary1 = a_33557126;
    }
    else {
    Temporary1 = b_33557127;
    }
    
    result_33557128 = Temporary1;
    break BeforeRet;
  };

  return result_33557128;

}

function addChar(x_33557437, c_33557438) {
    x_33557437.push(c_33557438);

  
}
var objectID_1191182513 = [0];

function setTheme(theme_553648134) {
    document.documentElement.setAttribute("data-theme", theme_553648134);
    window.localStorage.setItem("theme", theme_553648134);

  
}

function add_33556395(x_33556396, x_33556396_Idx, y_33556397) {
          if (x_33556396[x_33556396_Idx] === null) { x_33556396[x_33556396_Idx] = []; }
      var off = x_33556396[x_33556396_Idx].length;
      x_33556396[x_33556396_Idx].length += y_33556397.length;
      for (var i = 0; i < y_33556397.length; ++i) {
        x_33556396[x_33556396_Idx][off+i] = y_33556397.charCodeAt(i);
      }
    

  
}

function newSeq_33556941(len_33556943) {
  var result_33556944 = [];

    result_33556944 = new Array(len_33556943); for (var i = 0 ; i < len_33556943 ; ++i) { result_33556944[i] = null; }
  return result_33556944;

}

function unhandledException(e_33556671) {
    var buf_33556672 = [[]];
    if (!(((e_33556671.message).length == 0))) {
    buf_33556672[0].push.apply(buf_33556672[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556672[0].push.apply(buf_33556672[0], e_33556671.message);;
    }
    else {
    buf_33556672[0].push.apply(buf_33556672[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556672[0].push.apply(buf_33556672[0], [32,91]);;
    add_33556395(buf_33556672, 0, e_33556671.name);
    buf_33556672[0].push.apply(buf_33556672[0], [93,10]);;
    var cbuf_33556673 = toJSStr(buf_33556672[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556673);
  }
  else {
    throw cbuf_33556673;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557070) {
        if (a_33557070 > 2147483647 || a_33557070 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_301990095), 0, 2147483647), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_553649329 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553649329 < n_301990095)) break Label4;
            iHEX60gensym4_301990110 = i_553649329;
            result_301990092[result_301990092_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_301990092[result_301990092_Idx]).length - 1)] = x_301990093.charCodeAt(chckIndx(addInt(start_301990094, iHEX60gensym4_301990110), 0, (x_301990093).length - 1));
            i_553649329 = addInt(i_553649329, 1);
          }
      };
    };

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));

  
}

function HEX24_385875976(x_385875977) {
  var result_385875978 = [[]];

    addInt_301990129(result_385875978, 0, x_385875977);

  return result_385875978[0];

}

function isFatPointer_33557281(ti_33557282) {
  var result_33557283 = false;

  BeforeRet: {
    result_33557283 = !((ConstSet1[ti_33557282.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557283;

}

function nimCopyAux(dest_33557294, src_33557295, n_33557296) {
    switch (n_33557296.kind) {
    case 0:
      break;
    case 1:
            dest_33557294[n_33557296.offset] = nimCopy(dest_33557294[n_33557296.offset], src_33557295[n_33557296.offset], n_33557296.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557296.sons.length; i++) {
      nimCopyAux(dest_33557294, src_33557295, n_33557296.sons[i]);
    }
    
      break;
    case 3:
            dest_33557294[n_33557296.offset] = nimCopy(dest_33557294[n_33557296.offset], src_33557295[n_33557296.offset], n_33557296.typ);
      for (var i = 0; i < n_33557296.sons.length; ++i) {
        nimCopyAux(dest_33557294, src_33557295, n_33557296.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556834, a_33556835, b_33556836) {
    var Temporary1;

    if ((b_33556836 < a_33556835)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_385875976(i_33556834) || [],[32,110,111,116,32,105,110,32] || [],HEX24_385875976(a_33556835) || [],[32,46,46,32] || [],HEX24_385875976(b_33556836) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_268435501(message_268435504) {
    raiseException({message: nimCopy(null, message_268435504, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_268435499(msg_268435500) {
    sysFatal_268435501(msg_268435500);

  
}

function failedAssertImpl_268435541(msg_268435542) {
    raiseAssert_268435499(msg_268435542);

  
}

function onDOMLoaded(e_553648169) {
            
function HEX3Aanonymous_553648193(event_553648194) {
                event_553648194.target.parentNode.style.display = "none";
                event_553648194.target.parentNode.nextSibling.style.display = "inline";

              
            }

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_553648192 = null;
      var colontmp__553649320 = [];
      colontmp__553649320 = document.getElementsByClassName("pragmadots");
      var i_553649322 = 0;
      var L_553649323 = (colontmp__553649320).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649322 < L_553649323)) break Label3;
            pragmaDots_553648192 = colontmp__553649320[chckIndx(i_553649322, 0, (colontmp__553649320).length - 1)];
            pragmaDots_553648192.onclick = HEX3Aanonymous_553648193;
            i_553649322 = addInt(i_553649322, 1);
            if (!(((colontmp__553649320).length == L_553649323))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function isWhitespace_553648537(x_553648538) {
  var result_553648539 = false;

    result_553648539 = (((x_553648538.nodeName == "#text") && !/\S/.test(x_553648538.textContent)) || (x_553648538.nodeName == "#comment"));

  return result_553648539;

}

function toToc_553648540(x_553648541, father_553648542) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_553648541.nodeName == "UL")) {
    var f_553648550 = {heading: null, kids: [], sortId: (father_553648542.kids).length, doSort: false};
    var i_553648551 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_553648551 < x_553648541.childNodes.length)) break Label2;
          var nxt_553648552 = addInt(i_553648551, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_553648552 < x_553648541.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_553648537(x_553648541.childNodes[nxt_553648552]);                }              if (!Temporary5) break Label4;
                nxt_553648552 = addInt(nxt_553648552, 1);
              }
          };
            if (!(nxt_553648552 < x_553648541.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_553648541.childNodes[i_553648551].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_553648541.childNodes[i_553648551].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_553648541.childNodes[nxt_553648552].nodeName == "UL");            }          if (Temporary6) {
          var e_553648565 = {heading: x_553648541.childNodes[i_553648551].childNodes[0], kids: [], sortId: (f_553648550.kids).length, doSort: false};
          var it_553648566 = x_553648541.childNodes[nxt_553648552];
          Label9: {
            var j_553648571 = 0;
            var colontmp__553649336 = 0;
            colontmp__553649336 = it_553648566.childNodes.length;
            var i_553649337 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_553649337 < colontmp__553649336)) break Label11;
                  j_553648571 = i_553649337;
                  toToc_553648540(it_553648566.childNodes[j_553648571], e_553648565);
                  i_553649337 = addInt(i_553649337, 1);
                }
            };
          };
          f_553648550.kids.push(e_553648565);;
          i_553648551 = addInt(nxt_553648552, 1);
          }
          else {
            toToc_553648540(x_553648541.childNodes[i_553648551], f_553648550);
            i_553648551 = addInt(i_553648551, 1);
          }
          
        }
    };
    father_553648542.kids.push(f_553648550);;
    }
    else {
    if (isWhitespace_553648537(x_553648541)) {
    }
    else {
    if ((x_553648541.nodeName == "LI")) {
    var idx_553648589 = [];
    Label12: {
      var i_553648594 = 0;
      var colontmp__553649340 = 0;
      colontmp__553649340 = x_553648541.childNodes.length;
      var i_553649341 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_553649341 < colontmp__553649340)) break Label14;
            i_553648594 = i_553649341;
            if (!(isWhitespace_553648537(x_553648541.childNodes[i_553648594]))) {
            idx_553648589.push(i_553648594);;
            }
            
            i_553649341 = addInt(i_553649341, 1);
          }
      };
    };
      if (!((idx_553648589).length == 2)) Temporary15 = false; else {        Temporary15 = (x_553648541.childNodes[idx_553648589[chckIndx(1, 0, (idx_553648589).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_553648610 = {heading: x_553648541.childNodes[idx_553648589[chckIndx(0, 0, (idx_553648589).length - 1)]], kids: [], sortId: (father_553648542.kids).length, doSort: false};
    var it_553648611 = x_553648541.childNodes[idx_553648589[chckIndx(1, 0, (idx_553648589).length - 1)]];
    Label16: {
      var j_553648616 = 0;
      var colontmp__553649344 = 0;
      colontmp__553649344 = it_553648611.childNodes.length;
      var i_553649345 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_553649345 < colontmp__553649344)) break Label18;
            j_553648616 = i_553649345;
            toToc_553648540(it_553648611.childNodes[j_553648616], e_553648610);
            i_553649345 = addInt(i_553649345, 1);
          }
      };
    };
    father_553648542.kids.push(e_553648610);;
    }
    else {
      Label19: {
        var i_553648625 = 0;
        var colontmp__553649348 = 0;
        colontmp__553649348 = x_553648541.childNodes.length;
        var i_553649349 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_553649349 < colontmp__553649348)) break Label21;
              i_553648625 = i_553649349;
              toToc_553648540(x_553648541.childNodes[i_553648625], father_553648542);
              i_553649349 = addInt(i_553649349, 1);
            }
        };
      };
    }
    
    }
    else {
    father_553648542.kids.push({heading: x_553648541, kids: [], sortId: (father_553648542.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems_553648327(x_553648328, heading_553648329, items_553648330, items_553648330_Idx) {
  BeforeRet: {
    if ((x_553648328 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_553648328.heading == null)) && (x_553648328.heading.textContent == heading_553648329))) {
    Label1: {
      var i_553648347 = 0;
      var colontmp__553649352 = 0;
      colontmp__553649352 = (x_553648328.kids).length;
      var i_553649353 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649353 < colontmp__553649352)) break Label3;
            i_553648347 = i_553649353;
            items_553648330[items_553648330_Idx].push(x_553648328.kids[chckIndx(i_553648347, 0, (x_553648328.kids).length - 1)].heading);;
            i_553649353 = addInt(i_553649353, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_553648373 = null;
        var i_553649357 = 0;
        var L_553649358 = (x_553648328.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_553649357 < L_553649358)) break Label6;
              k_553648373 = x_553648328.kids[chckIndx(i_553649357, 0, (x_553648328.kids).length - 1)];
              extractItems_553648327(k_553648373, heading_553648329, items_553648330, items_553648330_Idx);
              i_553649357 = addInt(i_553649357, 1);
              if (!(((x_553648328.kids).length == L_553649358))) {
              failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree_553648258(tag_553648259, kids_553648260) {
  var result_553648261 = null;

    result_553648261 = document.createElement(tag_553648259);
    Label1: {
      var k_553648275 = null;
      var i_553649370 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649370 < (kids_553648260).length)) break Label3;
            k_553648275 = kids_553648260[chckIndx(i_553649370, 0, (kids_553648260).length - 1)];
            result_553648261.appendChild(k_553648275);
            i_553649370 = addInt(i_553649370, 1);
          }
      };
    };

  return result_553648261;

}

function text_553648283(s_553648284) {
  var result_553648285 = null;

    result_553648285 = document.createTextNode(s_553648284);

  return result_553648285;

}

function uncovered_553648729(x_553648730) {
    var Temporary1;

  var result_553648731 = null;

  BeforeRet: {
    if ((((x_553648730.kids).length == 0) && !((x_553648730.heading == null)))) {
    if (!(x_553648730.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_553648730;
    }
    else {
    Temporary1 = null;
    }
    
    result_553648731 = Temporary1;
    break BeforeRet;
    }
    
    result_553648731 = {heading: x_553648730.heading, kids: [], sortId: x_553648730.sortId, doSort: x_553648730.doSort};
    Label2: {
      var k_553648746 = null;
      var i_553649377 = 0;
      var L_553649378 = (x_553648730.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_553649377 < L_553649378)) break Label4;
            k_553648746 = x_553648730.kids[chckIndx(i_553649377, 0, (x_553648730.kids).length - 1)];
            var y_553648747 = uncovered_553648729(k_553648746);
            if (!((y_553648747 == null))) {
            result_553648731.kids.push(y_553648747);;
            }
            
            i_553649377 = addInt(i_553649377, 1);
            if (!(((x_553648730.kids).length == L_553649378))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_553648731.kids).length == 0)) {
    result_553648731 = null;
    }
    
  };

  return result_553648731;

}

function mergeTocs_553648759(orig_553648760, news_553648761) {
  var result_553648762 = null;

    result_553648762 = uncovered_553648729(orig_553648760);
    if ((result_553648762 == null)) {
    result_553648762 = news_553648761;
    }
    else {
      Label1: {
        var i_553648774 = 0;
        var colontmp__553649373 = 0;
        colontmp__553649373 = (news_553648761.kids).length;
        var i_553649374 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_553649374 < colontmp__553649373)) break Label3;
              i_553648774 = i_553649374;
              result_553648762.kids.push(news_553648761.kids[chckIndx(i_553648774, 0, (news_553648761.kids).length - 1)]);;
              i_553649374 = addInt(i_553649374, 1);
            }
        };
      };
    }
    

  return result_553648762;

}

function buildToc_553648779(orig_553648780, types_553648781, procs_553648782) {
  var result_553648783 = null;

    var newStuff_553648788 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_553648792 = null;
      var i_553649365 = 0;
      var L_553649366 = (types_553648781).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649365 < L_553649366)) break Label3;
            t_553648792 = types_553648781[chckIndx(i_553649365, 0, (types_553648781).length - 1)];
            var c_553648797 = {heading: t_553648792.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_553648792.__karaxMarker__ = true;
            Label4: {
              var p_553648801 = null;
              var i_553649362 = 0;
              var L_553649363 = (procs_553648782).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_553649362 < L_553649363)) break Label6;
                    p_553648801 = procs_553648782[chckIndx(i_553649362, 0, (procs_553648782).length - 1)];
                    if (!(p_553648801.hasOwnProperty('__karaxMarker__'))) {
                    var xx_553648802 = p_553648801.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_553648802).length == 1) && (xx_553648802[chckIndx(0, 0, (xx_553648802).length - 1)].textContent == t_553648792.textContent))) {
                    var q_553648807 = tree_553648258("A", [text_553648283(p_553648801.title)]);
                    q_553648807.setAttribute("href", p_553648801.getAttribute("href"));
                    c_553648797.kids.push({heading: q_553648807, kids: [], sortId: 0, doSort: false});;
                    p_553648801.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_553649362 = addInt(i_553649362, 1);
                    if (!(((procs_553648782).length == L_553649363))) {
                    failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_553648788.kids.push(c_553648797);;
            i_553649365 = addInt(i_553649365, 1);
            if (!(((types_553648781).length == L_553649366))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553648783 = mergeTocs_553648759(orig_553648780, newStuff_553648788);

  return result_553648783;

}

function add_553648276(parent_553648277, kid_553648278) {
    if (((parent_553648277.nodeName == "TR") && ((kid_553648278.nodeName == "TD") || (kid_553648278.nodeName == "TH")))) {
    var k_553648279 = document.createElement("TD");
    k_553648279.appendChild(kid_553648278);
    parent_553648277.appendChild(k_553648279);
    }
    else {
    parent_553648277.appendChild(kid_553648278);
    }
    

  
}

function setClass_553648280(e_553648281, value_553648282) {
    e_553648281.setAttribute("class", value_553648282);

  
}

function toHtml_553648406(x_553648407, isRoot_553648408) {
    
function HEX3Aanonymous_553648426(a_553648427, b_553648428) {
      var result_553648429 = 0;

      BeforeRet: {
        if ((!((a_553648427.heading == null)) && !((b_553648428.heading == null)))) {
        var x_553648438 = a_553648427.heading.textContent;
        var y_553648439 = b_553648428.heading.textContent;
        if ((x_553648438 < y_553648439)) {
        result_553648429 = -1;
        break BeforeRet;
        }
        
        if ((y_553648439 < x_553648438)) {
        result_553648429 = 1;
        break BeforeRet;
        }
        
        result_553648429 = 0;
        break BeforeRet;
        }
        else {
          result_553648429 = subInt(a_553648427.sortId, b_553648428.sortId);
          break BeforeRet;
        }
        
      };

      return result_553648429;

    }

  var result_553648409 = null;

  BeforeRet: {
    if ((x_553648407 == null)) {
    result_553648409 = null;
    break BeforeRet;
    }
    
    if (((x_553648407.kids).length == 0)) {
    if ((x_553648407.heading == null)) {
    result_553648409 = null;
    break BeforeRet;
    }
    
    result_553648409 = x_553648407.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_553648409 = tree_553648258("DIV", []);
    if ((!((x_553648407.heading == null)) && !(x_553648407.heading.hasOwnProperty('__karaxMarker__')))) {
    add_553648276(result_553648409, x_553648407.heading.cloneNode(true));
    }
    
    var ul_553648425 = tree_553648258("UL", []);
    if (isRoot_553648408) {
    setClass_553648280(ul_553648425, "simple simple-toc");
    }
    else {
    setClass_553648280(ul_553648425, "simple");
    }
    
    if (x_553648407.doSort) {
    x_553648407.kids.sort(HEX3Aanonymous_553648426);
    }
    
    Label1: {
      var k_553648451 = null;
      var i_553649381 = 0;
      var L_553649382 = (x_553648407.kids).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649381 < L_553649382)) break Label3;
            k_553648451 = x_553648407.kids[chckIndx(i_553649381, 0, (x_553648407.kids).length - 1)];
            var y_553648452 = toHtml_553648406(k_553648451, false);
            if (!((y_553648452 == null))) {
            add_553648276(ul_553648425, tree_553648258("LI", [y_553648452]));
            }
            
            i_553649381 = addInt(i_553649381, 1);
            if (!(((x_553648407.kids).length == L_553649382))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_553648425.childNodes.length == 0))) {
    add_553648276(result_553648409, ul_553648425);
    }
    
    if ((result_553648409.childNodes.length == 0)) {
    result_553648409 = null;
    }
    
  };

  return result_553648409;

}

function replaceById_553648286(id_553648287, newTree_553648288) {
    var x_553648289 = document.getElementById(id_553648287);
    x_553648289.parentNode.replaceChild(newTree_553648288, x_553648289);
    newTree_553648288.id = id_553648287;

  
}

function togglevis_553648837(d_553648838) {
    if ((d_553648838.style.display == "none")) {
    d_553648838.style.display = "inline";
    }
    else {
      d_553648838.style.display = "none";
    }
    

  
}

function groupBy(value_553648840) {
    var toc_553648841 = document.getElementById("toc-list");
    if ((alternative_553648836[0] == null)) {
    var tt_553648849 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc_553648540(toc_553648841, tt_553648849);
    tt_553648849 = tt_553648849.kids[chckIndx(0, 0, (tt_553648849.kids).length - 1)];
    var types_553648854 = [[]];
    var procs_553648859 = [[]];
    extractItems_553648327(tt_553648849, "Types", types_553648854, 0);
    extractItems_553648327(tt_553648849, "Procs", procs_553648859, 0);
    extractItems_553648327(tt_553648849, "Converters", procs_553648859, 0);
    extractItems_553648327(tt_553648849, "Methods", procs_553648859, 0);
    extractItems_553648327(tt_553648849, "Templates", procs_553648859, 0);
    extractItems_553648327(tt_553648849, "Macros", procs_553648859, 0);
    extractItems_553648327(tt_553648849, "Iterators", procs_553648859, 0);
    var ntoc_553648860 = buildToc_553648779(tt_553648849, types_553648854[0], procs_553648859[0]);
    var x_553648861 = toHtml_553648406(ntoc_553648860, true);
    alternative_553648836[0] = tree_553648258("DIV", [x_553648861]);
    }
    
    if ((value_553648840 == "type")) {
    replaceById_553648286("tocRoot", alternative_553648836[0]);
    }
    else {
    replaceById_553648286("tocRoot", tree_553648258("DIV", []));
    }
    
    togglevis_553648837(document.getElementById("toc-list"));

  
}

function HEX5BHEX5D_721421621(s_721421624, x_721421625) {
  var result_721421626 = [];

    var a_721421628 = x_721421625.a;
    var L_721421630 = addInt(subInt(subInt((s_721421624).length, x_721421625.b), a_721421628), 1);
    result_721421626 = nimCopy(null, mnewString(chckRange(L_721421630, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_721421635 = 0;
      var i_553649391 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649391 < L_721421630)) break Label3;
            i_721421635 = i_553649391;
            result_721421626[chckIndx(i_721421635, 0, (result_721421626).length - 1)] = s_721421624[chckIndx(addInt(i_721421635, a_721421628), 0, (s_721421624).length - 1)];
            i_553649391 = addInt(i_553649391, 1);
          }
      };
    };

  return result_721421626;

}

function HEX2EHEX2E_956301415(a_956301418, b_956301419) {
  var result_956301422 = ({a: 0, b: 0});

    result_956301422 = nimCopy(result_956301422, {a: a_956301418, b: b_956301419}, NTI956301399);

  return result_956301422;

}
async function loadIndex_553649056() {
  var result_553649058 = null;

  BeforeRet: {
    var indexURL_553649064 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_553649090 = HEX5BHEX5D_721421621(cstrToNimstr(indexURL_553649064), HEX2EHEX2E_956301415(0, 14));
    var resp_553649102 = (await (await fetch(indexURL_553649064)).text());
    var indexElem_553649103 = document.createElement("div");
    indexElem_553649103.innerHTML = resp_553649102;
    Label1: {
      var href_553649125 = null;
      var colontmp__553649385 = [];
      colontmp__553649385 = indexElem_553649103.getElementsByClassName("reference");
      var i_553649387 = 0;
      var L_553649388 = (colontmp__553649385).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649387 < L_553649388)) break Label3;
            href_553649125 = colontmp__553649385[chckIndx(i_553649387, 0, (colontmp__553649385).length - 1)];
            href_553649125.setAttribute("href", toJSStr((rootURL_553649090 || []).concat(cstrToNimstr(href_553649125.getAttribute("href")) || [])));
            db_553648878[0].push(href_553649125);;
            contents_553648879[0].push(href_553649125.getAttribute("data-doc-search-tag"));;
            i_553649387 = addInt(i_553649387, 1);
            if (!(((colontmp__553649385).length == L_553649388))) {
            failedAssertImpl_268435541(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553649058 = undefined;
    break BeforeRet;
  };

  return result_553649058;

}

function then_553649234(future_553649237, onSuccess_553649238, onReject_553649239) {
  var result_553649240 = null;

  BeforeRet: {
    var ret_553649250 = null;
    ret_553649250 = future_553649237.then(onSuccess_553649238, onReject_553649239)
    result_553649240 = ret_553649250;
    break BeforeRet;
  };

  return result_553649240;

}

function nsuToLowerAsciiChar(c_721420373) {
  var result_721420374 = 0;

    if ((ConstSet2[c_721420373] != undefined)) {
    result_721420374 = (c_721420373 ^ 32);
    }
    else {
      result_721420374 = c_721420373;
    }
    

  return result_721420374;

}

function fuzzyMatch_704643088(pattern_704643089, str_704643090) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_704643093 = {Field0: 0, Field1: false};

    var scoreState_704643094 = -100;
    var headerMatched_704643095 = false;
    var unmatchedLeadingCharCount_704643096 = 0;
    var consecutiveMatchCount_704643097 = 0;
    var strIndex_704643098 = 0;
    var patIndex_704643099 = 0;
    var score_704643100 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_704643098 < ((str_704643090) == null ? 0 : (str_704643090).length)) && (patIndex_704643099 < ((pattern_704643089) == null ? 0 : (pattern_704643089).length)))) break Label2;
          Label3: {
            var patternChar_704643103 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(patIndex_704643099, 0, (pattern_704643089).length - 1)));
            var strChar_704643104 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1)));
            if ((ConstSet3[patternChar_704643103] != undefined)) {
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_704643104] != undefined)) {
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((!(headerMatched_704643095) && (strChar_704643104 == 58))) {
            headerMatched_704643095 = true;
            scoreState_704643094 = -100;
            score_704643100 = ((Math.floor((0.5 * score_704643100))) | 0);
            patIndex_704643099 = 0;
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((strChar_704643104 == patternChar_704643103)) {
            switch (scoreState_704643094) {
            case -100:
            case 20:
              scoreState_704643094 = 10;
              break;
            case 0:
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_704643097 = addInt(consecutiveMatchCount_704643097, 1);
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, mulInt(5, consecutiveMatchCount_704643097));
              if ((scoreState_704643094 == 10)) {
              score_704643100 = addInt(score_704643100, 10);
              }
              
              var onBoundary_704643156 = (patIndex_704643099 == ((pattern_704643089) == null ? -1 : (pattern_704643089).length - 1));
              if ((!(onBoundary_704643156) && (strIndex_704643098 < ((str_704643090) == null ? -1 : (str_704643090).length - 1)))) {
              var nextPatternChar_704643157 = nsuToLowerAsciiChar(pattern_704643089.charCodeAt(chckIndx(addInt(patIndex_704643099, 1), 0, (pattern_704643089).length - 1)));
              var nextStrChar_704643158 = nsuToLowerAsciiChar(str_704643090.charCodeAt(chckIndx(addInt(strIndex_704643098, 1), 0, (str_704643090).length - 1)));
              if (!!((ConstSet5[nextStrChar_704643158] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_704643158 == nextPatternChar_704643157));              }              onBoundary_704643156 = Temporary4;
              }
              
              if (onBoundary_704643156) {
              scoreState_704643094 = 20;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            case -1:
            case -3:
              if (!((ConstSet6[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_704643090.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_704643090).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_704643182 = Temporary5;
              if (isLeadingChar_704643182) {
              scoreState_704643094 = 10;
              }
              else {
                scoreState_704643094 = 0;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            }
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            }
            else {
              switch (scoreState_704643094) {
              case -100:
                scoreState_704643094 = -3;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              case 5:
                scoreState_704643094 = -1;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                consecutiveMatchCount_704643097 = 0;
                break;
              case -3:
                if ((unmatchedLeadingCharCount_704643096 < 3)) {
                scoreState_704643094 = -3;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                }
                
                unmatchedLeadingCharCount_704643096 = addInt(unmatchedLeadingCharCount_704643096, 1);
                break;
              default: 
                scoreState_704643094 = -1;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              }
            }
            
            strIndex_704643098 = addInt(strIndex_704643098, 1);
          };
        }
    };
      if (!(patIndex_704643099 == ((pattern_704643089) == null ? 0 : (pattern_704643089).length))) Temporary7 = false; else {        if ((strIndex_704643098 == ((str_704643090) == null ? 0 : (str_704643090).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_704643090.charCodeAt(chckIndx(strIndex_704643098, 0, (str_704643090).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_704643100 = addInt(score_704643100, 10);
    }
    
    var colontmp__553649404 = nimMax(0, score_704643100);
    var colontmp__553649405 = (0 < score_704643100);
    result_704643093 = nimCopy(result_704643093, {Field0: colontmp__553649404, Field1: colontmp__553649405}, NTI704643086);

  return result_704643093;

}

function escapeCString_553648880(x_553648881, x_553648881_Idx) {
    var s_553648882 = [];
    Label1: {
      var c_553648883 = 0;
      var iHEX60gensym6_553649408 = 0;
      var nHEX60gensym6_553649409 = ((x_553648881[x_553648881_Idx]) == null ? 0 : (x_553648881[x_553648881_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym6_553649408 < nHEX60gensym6_553649409)) break Label3;
            c_553648883 = x_553648881[x_553648881_Idx].charCodeAt(chckIndx(iHEX60gensym6_553649408, 0, (x_553648881[x_553648881_Idx]).length - 1));
            switch (c_553648883) {
            case 60:
              s_553648882.push.apply(s_553648882, [38,108,116,59]);;
              break;
            case 62:
              s_553648882.push.apply(s_553648882, [38,103,116,59]);;
              break;
            default: 
              addChar(s_553648882, c_553648883);;
              break;
            }
            iHEX60gensym6_553649408 = addInt(iHEX60gensym6_553649408, 1);
          }
      };
    };
    x_553648881[x_553648881_Idx] = toJSStr(s_553648882);

  
}

function dosearch_553648884(value_553648885) {
    
function HEX3Aanonymous_553648912(a_553648917, b_553648918) {
      var result_553648923 = 0;

        result_553648923 = subInt(b_553648918["Field1"], a_553648917["Field1"]);

      return result_553648923;

    }

  var result_553648886 = null;

  BeforeRet: {
    if (((db_553648878[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_553648890 = tree_553648258("UL", []);
    result_553648886 = tree_553648258("DIV", []);
    setClass_553648280(result_553648886, "search_results");
    var matches_553648895 = [];
    Label1: {
      var i_553648903 = 0;
      var colontmp__553649395 = 0;
      colontmp__553649395 = (db_553648878[0]).length;
      var i_553649396 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649396 < colontmp__553649395)) break Label3;
            i_553648903 = i_553649396;
            Label4: {
              var c_553648904 = contents_553648879[0][chckIndx(i_553648903, 0, (contents_553648879[0]).length - 1)];
              if (((c_553648904 == "Examples") || (c_553648904 == "PEG construction"))) {
              break Label4;
              }
              
              var tmpTuple_553648905 = fuzzyMatch_704643088(value_553648885, c_553648904);
              var score_553648906 = tmpTuple_553648905["Field0"];
              var matched_553648907 = tmpTuple_553648905["Field1"];
              if (matched_553648907) {
              matches_553648895.push({Field0: db_553648878[0][chckIndx(i_553648903, 0, (db_553648878[0]).length - 1)], Field1: score_553648906});;
              }
              
            };
            i_553649396 = addInt(i_553649396, 1);
          }
      };
    };
    matches_553648895.sort(HEX3Aanonymous_553648912);
    Label5: {
      var i_553648940 = 0;
      var colontmp__553649399 = 0;
      colontmp__553649399 = nimMin((matches_553648895).length, 29);
      var i_553649400 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_553649400 < colontmp__553649399)) break Label7;
            i_553648940 = i_553649400;
            matches_553648895[chckIndx(i_553648940, 0, (matches_553648895).length - 1)]["Field0"].innerHTML = matches_553648895[chckIndx(i_553648940, 0, (matches_553648895).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString_553648880(matches_553648895[chckIndx(i_553648940, 0, (matches_553648895).length - 1)]["Field0"], "innerHTML");
            add_553648276(ul_553648890, tree_553648258("LI", [matches_553648895[chckIndx(i_553648940, 0, (matches_553648895).length - 1)]["Field0"]]));
            i_553649400 = addInt(i_553649400, 1);
          }
      };
    };
    if ((ul_553648890.childNodes.length == 0)) {
    add_553648276(result_553648886, tree_553648258("B", [text_553648283("no search results")]));
    }
    else {
      add_553648276(result_553648886, tree_553648258("B", [text_553648283("search results")]));
      add_553648276(result_553648886, ul_553648890);
    }
    
  };

  return result_553648886;

}

function search() {
    
function wrapper_553649219() {
        var elem_553649220 = document.getElementById("searchInput");
        var value_553649221 = elem_553649220.value;
        if (!((((value_553649221) == null ? 0 : (value_553649221).length) == 0))) {
        if ((oldtoc_553649214[0] == null)) {
        oldtoc_553649214[0] = document.getElementById("tocRoot");
        }
        
        var results_553649225 = dosearch_553648884(value_553649221);
        replaceById_553648286("tocRoot", results_553649225);
        }
        else {
        if (!((oldtoc_553649214[0] == null))) {
        replaceById_553648286("tocRoot", oldtoc_553649214[0]);
        }
        }

      
    }

    if ((loadIndexFut_553649217[0] == null)) {
    loadIndexFut_553649217[0] = loadIndex_553649056();
    var _ = then_553649234(loadIndexFut_553649217[0], wrapper_553649219, null);
    }
    
    if (!((timer_553649215[0] == null))) {
    clearTimeout(timer_553649215[0]);
    }
    
    timer_553649215[0] = setTimeout(wrapper_553649219, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var t_553648167 = window.localStorage.getItem("theme");
if ((t_553648167 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_553648167;
}

setTheme(Temporary1);
var alternative_553648836 = [null];
var db_553648878 = [[]];
var contents_553648879 = [[]];
var oldtoc_553649214 = [null];
var timer_553649215 = [null];
var loadIndexFut_553649217 = [null];
copyToClipboard();
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
